### ISSUE TITLE
Unable to write jest test cases for saga-slice 

### ISSUE THREAD

**Issue by Pooja-khandelwal-wawa** [damusix/saga-slice#3]
hi damusix,

I am facing issue while writing jest test cases for saga-slice as in its dist/cjs.js file: 
  var moduleReducer = function moduleReducer() {
.....
      if (typeof reducer === 'function') {
        return immer["default"](state, function (draft) {
          return reducer(draft, payload);
        });
      }..}

i am getting error : immer.default is not a function. If I remove ["default"], things are working as expected. Kindly take a look in this and help

**Comment by damusix** [comment]
@Pooja-khandelwal-wawa Thank you for submitting a request. Can you create an example on codepen or a public github repo with some sample code?

**Comment by Pooja-khandelwal-wawa** [comment]
Hi Alonso,

I have resolved this issue. Now, I am able to write the test cases for saga-slice.

Thanks
Pooja Khandelwal
